

create table "users" (
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR
);

CREATE TABLE "users2" (
	--* a pasar de ser automatico permite ingresar el codigo pero presenta el mismo inconveniente que el tipo de dato serial al momento de que colicione el valor de la secuencia interna con el valor que ingreso el usuario
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"username" VARCHAR
);

CREATE TABLE "users3" (
	--* always no permite el ingreso del id de forma manual
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"username" VARCHAR
);

CREATE TABLE "users4" (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY 
	--*empieza desde el 100 y se aumenta en 2 en 2
	(START WITH 100 INCREMENT BY 2
),
	"username" VARCHAR
);










